services:
  postgres:
    image: postgres:15-alpine
    container_name: ddd_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ddd_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_ddd_db:/var/lib/postgresql/data

volumes:
  postgres_ddd_db:
